import Head from "next/head";
import Link from "next/link";
import { BookOpen, CheckCircle2, Trash2, WifiOff } from "lucide-react";
import { removeOfflineCourse, useOfflineCourses } from "@/lib/offline";

export default function OfflineLibrary() {
  const courses = useOfflineCourses();
  return <><Head><title>Offline Library | CODES</title></Head><main className="min-h-screen bg-slate-50"><section className="bg-slate-950 px-4 py-9 text-white"><div className="mx-auto max-w-6xl"><p className="flex items-center gap-2 text-xs font-bold tracking-widest text-blue-300"><WifiOff size={16}/>OFFLINE MODE</p><h1 className="mt-2 text-3xl font-bold">Your offline library</h1><p className="mt-2 text-sm text-slate-300">Downloaded text, images and course outlines. Videos require internet.</p></div></section><section className="mx-auto max-w-6xl px-4 py-8">{courses.length?<div className="grid gap-5 md:grid-cols-2">{courses.map((course)=><article key={course.id} className="overflow-hidden rounded-xl border bg-white shadow-sm">{course.image?<img src={course.image} alt="" className="h-40 w-full object-cover"/>:<div className="grid h-32 place-items-center bg-blue-50"><BookOpen className="text-blue-700" size={36}/></div>}<div className="p-5"><div className="flex items-center gap-2 text-xs font-bold text-emerald-700"><CheckCircle2 size={15}/>Available Offline</div><h2 className="mt-2 text-xl font-bold">{course.title}</h2><p className="mt-1 text-xs font-semibold text-blue-700">{course.provider} · {course.type}</p><p className="mt-3 text-sm leading-6 text-slate-600">{course.description}</p><h3 className="mt-5 font-bold">Course outline</h3><div className="mt-2 space-y-2">{course.modules.map((module,index)=><details key={module.title} className="rounded-lg border p-3"><summary className="cursor-pointer text-sm font-semibold">{index+1}. {module.title}</summary><p className="mt-2 text-sm text-slate-600">{module.description}</p><p className="mt-1 text-xs text-slate-500">{module.hours} hours · {module.quizzes} quizzes · {module.projects} projects</p></details>)}</div><div className="mt-4 flex flex-wrap gap-2">{course.skills.map((skill)=><span key={skill} className="rounded-full bg-blue-50 px-2.5 py-1 text-xs text-blue-800">{skill}</span>)}</div><button onClick={()=>removeOfflineCourse(course.id)} className="mt-5 flex items-center gap-2 text-sm font-semibold text-red-600"><Trash2 size={16}/>Remove download</button></div></article>)}</div>:<div className="rounded-xl border border-dashed bg-white p-12 text-center"><WifiOff className="mx-auto text-slate-400" size={42}/><h2 className="mt-3 text-xl font-bold">No offline courses yet</h2><p className="mt-2 text-sm text-slate-600">Open a course and choose “Download for offline”.</p><Link href="/catalog" className="mt-5 inline-block rounded-lg bg-blue-700 px-5 py-2.5 font-bold text-white">Browse courses</Link></div>}</section></main></>;
}
